default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: 5432

development:
  <<: *default
  database: iadvize_dev

test:
  <<: *default
  database: iadvize_test

production:
  <<: *default
  database: iadvize_prod